package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CControlChoice extends Structure {
	/// be used as an index into CControl#choices#list[].
	public int index;
	/**
	 * This member is never NULL.<br>
	 * C type : char*
	 */
	public Pointer name;
	public CControlChoice() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"index", "name"});
	}
	/**
	 * @param index be used as an index into CControl#choices#list[].<br>
	 * @param name This member is never NULL.<br>
	 * C type : char*
	 */
	public CControlChoice(int index, Pointer name) {
		super();
		this.index = index;
		this.name = name;
		initFieldOrder();
	}
	public static class ByReference extends CControlChoice implements Structure.ByReference {
		
	};
	public static class ByValue extends CControlChoice implements Structure.ByValue {
		
	};
}
