package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CControlValue extends Structure {
	/**
	 * valid. The type is a duplicate of the corresponding CControl#type value.<br>
	 * @see CControlType<br>
	 * C type : CControlType
	 */
	public int type;
	public int value;
	public CControlValue() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"type", "value"});
	}
	/**
	 * @param type valid. The type is a duplicate of the corresponding CControl#type value.<br>
	 * @see CControlType<br>
	 * C type : CControlType
	 */
	public CControlValue(int type, int value) {
		super();
		this.type = type;
		this.value = value;
		initFieldOrder();
	}
	public static class ByReference extends CControlValue implements Structure.ByReference {
		
	};
	public static class ByValue extends CControlValue implements Structure.ByValue {
		
	};
}
