package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CDynctrlMessage extends Structure {
	/// Line number that the message concerns
	public int line;
	/// Column that the message concerns
	public int col;
	/**
	 * Severity level<br>
	 * @see CDynctrlMessageSeverity<br>
	 * C type : CDynctrlMessageSeverity
	 */
	public int severity;
	/**
	 * Pointer to the message text<br>
	 * C type : char*
	 */
	public Pointer text;
	public CDynctrlMessage() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"line", "col", "severity", "text"});
	}
	/**
	 * @param line Line number that the message concerns<br>
	 * @param col Column that the message concerns<br>
	 * @param severity Severity level<br>
	 * @see CDynctrlMessageSeverity<br>
	 * C type : CDynctrlMessageSeverity<br>
	 * @param text Pointer to the message text<br>
	 * C type : char*
	 */
	public CDynctrlMessage(int line, int col, int severity, Pointer text) {
		super();
		this.line = line;
		this.col = col;
		this.severity = severity;
		this.text = text;
		initFieldOrder();
	}
	public static class ByReference extends CDynctrlMessage implements Structure.ByReference {
		
	};
	public static class ByValue extends CDynctrlMessage implements Structure.ByValue {
		
	};
}
