package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CDynctrlInfoListStats extends Structure {
	/// Number of elements in the list that were processed successfully
	public int successful;
	/// Number of elements in the list that could not be processed successfully
	public int failed;
	public CDynctrlInfoListStats() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"successful", "failed"});
	}
	/**
	 * @param successful Number of elements in the list that were processed successfully<br>
	 * @param failed Number of elements in the list that could not be processed successfully
	 */
	public CDynctrlInfoListStats(int successful, int failed) {
		super();
		this.successful = successful;
		this.failed = failed;
		initFieldOrder();
	}
	public static class ByReference extends CDynctrlInfoListStats implements Structure.ByReference {
		
	};
	public static class ByValue extends CDynctrlInfoListStats implements Structure.ByValue {
		
	};
}
