package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CEvent extends Structure {
	/**
	 * Unique identifier of the event<br>
	 * @see CEventId<br>
	 * C type : CEventId
	 */
	public int id;
	/**
	 * Human-readable name of the event<br>
	 * C type : char*
	 */
	public Pointer name;
	/**
	 * Flags descripting properties of the event<br>
	 * @see CEventFlags<br>
	 * C type : CEventFlags
	 */
	public int flags;
	public CEvent() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"id", "name", "flags"});
	}
	/**
	 * @param id Unique identifier of the event<br>
	 * @see CEventId<br>
	 * C type : CEventId<br>
	 * @param name Human-readable name of the event<br>
	 * C type : char*<br>
	 * @param flags Flags descripting properties of the event<br>
	 * @see CEventFlags<br>
	 * C type : CEventFlags
	 */
	public CEvent(int id, Pointer name, int flags) {
		super();
		this.id = id;
		this.name = name;
		this.flags = flags;
		initFieldOrder();
	}
	public static class ByReference extends CEvent implements Structure.ByReference {
		
	};
	public static class ByValue extends CEvent implements Structure.ByValue {
		
	};
}
