package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CFrameSize extends Structure {
	/**
	 * Type of the frame size(s) described (discrete, continuous, step-wise)<br>
	 * @see CFrameSizeTypes<br>
	 * C type : CFrameSizeTypes
	 */
	public int type;
	public CFrameSize() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"type"});
	}
	/**
	 * @param type Type of the frame size(s) described (discrete, continuous, step-wise)<br>
	 * @see CFrameSizeTypes<br>
	 * C type : CFrameSizeTypes
	 */
	public CFrameSize(int type) {
		super();
		this.type = type;
		initFieldOrder();
	}
	public static class ByReference extends CFrameSize implements Structure.ByReference {
		
	};
	public static class ByValue extends CFrameSize implements Structure.ByValue {
		
	};
}
