package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CUSBInfo extends Structure {
	/// The vendor ID.
	public short vendor;
	/// The product ID.
	public short product;
	/// The product revision number.
	public short release;
	public CUSBInfo() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"vendor", "product", "release"});
	}
	/**
	 * @param vendor The vendor ID.<br>
	 * @param product The product ID.<br>
	 * @param release The product revision number.
	 */
	public CUSBInfo(short vendor, short product, short release) {
		super();
		this.vendor = vendor;
		this.product = product;
		this.release = release;
		initFieldOrder();
	}
	public static class ByReference extends CUSBInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends CUSBInfo implements Structure.ByValue {
		
	};
}
