package com.eucalyptus.eucabot.webcam;
import com.sun.jna.Structure;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.free.fr/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class CVersionNumber extends Structure {
	/// Major version number
	public int major;
	/// Minor version number
	public int minor;
	public CVersionNumber() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new java.lang.String[]{"major", "minor"});
	}
	/**
	 * @param major Major version number<br>
	 * @param minor Minor version number
	 */
	public CVersionNumber(int major, int minor) {
		super();
		this.major = major;
		this.minor = minor;
		initFieldOrder();
	}
	public static class ByReference extends CVersionNumber implements Structure.ByReference {
		
	};
	public static class ByValue extends CVersionNumber implements Structure.ByValue {
		
	};
}
